apiVersion: v1
kind: Pod
metadata:
  name: cimple-front
spec:
  containers:
  - name: cimple-front
    image: taksan/cimple-front:v2
    ports:
    - containerPort: 80
      name: http
    env:
    - name: BACKEND_URL
      value: http://localhost:8081
