apiVersion: batch/v1
kind: Job
metadata:
 name: sample-job
spec:
 template:
   spec:
     containers:
     - name: task
       image: busybox
       args:
       - sh
       - -c
       - echo "This is a sample job"
     restartPolicy: Never
 backoffLimit: 0
