apiVersion: v1
kind: Pod
metadata:
  name: cimple-front
spec:
  containers:
  - name: cimple-front
    image: taksan/cimple-front:v1
    ports:
    - containerPort: 80
      name: http
    env:
    - name: BACKEND_URL
      value: http://localhost:8081
---
apiVersion: v1
kind: Pod
metadata:
  name: cimple-back
spec:
  containers:
   - name: cimple-back
    image: taksan/cimple-back:v1
    ports:
    - containerPort: 8000
      name: http
    env:
    - name: RUN_WITHOUT_DATABASE
      value: "true"
---
apiVersion: v1
kind: Pod
metadata:
 name: cimple-eviewer
spec:
  containers:
  - name: cimple-eviewer
    image: taksan/cimple-eviewer:v1
    ports:
    - containerPort: 5000
      name: http
    env:
    - name: CONF_FILE
      value: /app/config.json
