apiVersion: v1
kind: Pod
metadata:
 name: sample-pod
spec:
 containers:
 - name: readiness
   image: nginx
   readinessProbe:
     httpGet:
       path: /
       port: 80
     initialDelaySeconds: 5
     periodSeconds: 5
