apiVersion: v1
kind: Service
metadata:
  name: cimple-front
spec:
  selector:
    app: cimple-front
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: http
      nodePort: 32000
