apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: job-executor
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create", "get", "list"]
  # as roles abaixo não são necessárias para o back, mas seriam necessárias para ver logs
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["list"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get"]