apiVersion: apps/v1
kind: Deployment
metadata:
  name: cimple-back-deployment
  labels:
    app: cimple-back
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cimple-back
  template:
    metadata:
      name: cimple-back
      labels:
        app: cimple-back
    spec:
      volumes:
        - name: config-data
          emptyDir: {}
        - name: job-executor
          configMap:
            name: job-executor
            items:
              - key: job-executor.sh
                path: job-executor.sh

      initContainers:
        - name: init-config
          image: alpine
          command:
            - sh
            - -c
            - |
              cat <<EOF > /opt/config.json
              {
                "events_file": "/opt/audit_events.log",
                "peer_url" : "http://cimple-eviewer/api/events"
              }
              EOF
          volumeMounts:
            - name: config-data
              mountPath: /opt/
            - name: job-executor
              mountPath: /tmp/job-executor.sh
              subPath: job-executor.sh
      containers:
        - name: cimple-back
          image: taksan/cimple-back:v2
          ports:
            - containerPort: 8000
              name: http
          env:
            - name: RUN_WITHOUT_DATABASE
              value: "true"
            - name: TASK_EXECUTOR
              value: /app/job-executor.sh
          volumeMounts:
            - name: config-data
              mountPath: /app/logs

          startupProbe:
            httpGet:
              path: /health
              port: http
            periodSeconds: 10
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /health
              port: http
            failureThreshold: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: http
            failureThreshold: 30
            periodSeconds: 10
        - name: cimple-eviewer-collector
          image: taksan/cimple-eviewer-collector:v1
          volumeMounts:
            - name: config-data
              mountPath: /opt/
