apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: backend-sa-rolebinding-job-executor
  namespace: dev
subjects:
  - kind: ServiceAccount
    name: backend-sa
roleRef:
  kind: Role
  name: job-executor
  apiGroup: rbac.authorization.k8s.io
