apiVersion: apps/v1
kind: Deployment
metadata:
  name: cimple-store-deployment
  labels:
    app: cimple-store
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cimple-store
  template:
    metadata:
      name: cimple-store
      labels:
        app: cimple-store
    spec:
      volumes:
        - name: cimple-store-data
          persistentVolumeClaim:
            claimName: cimple-store-pvc
      # securityContext:
      #   fsGroup: 1001
      containers:
        - name: cimple-store
          image: taksan/cimple-store:v1
          ports:
            - containerPort: 8001
              name: http
          volumeMounts:
            - name: cimple-store-data
              mountPath: /app/data
          env:
            - name: STORE_USER
              value: storeuser
            - name: STORE_PASS
              value: storepass
---
apiVersion: v1
kind: Service
metadata:
  name: cimple-store
spec:
  selector:
    app: cimple-store
  ports:
    - protocol: TCP
      port: 80
      targetPort: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cimple-store
spec:
  ingressClassName: nginx
  rules:
    - host: store.dev.cimple.bootcamp
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cimple-store
                port:
                  number: 80
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: cimple-store-pv
spec:
  storageClassName: manual
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cimple-store-pvc
  annotations:
    volumeType: local
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 10Mi
