apiVersion: apps/v1
kind: Deployment
metadata:
  name: cimple-back-deployment
  namespace: dev
  labels:
    app: cimple-back
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cimple-back
  template:
    metadata:
      name: cimple-back
      labels:
        app: cimple-back
    spec:
      serviceAccount: backend-sa
      volumes:
        - name: config-data
          emptyDir: {}
        - name: logs
          emptyDir: {}
      initContainers:
        - name: init-config
          image: alpine
          command:
            - sh
            - -c
            - |
              cat <<EOF > /opt/config.json
              {
                "events_file": "/app/logs/audit_events.log",
                "peer_url" : "http://cimple-eviewer.audit/api/events"
              }
              EOF
          volumeMounts:
            - name: config-data
              mountPath: /opt/
      containers:
        - name: cimple-back
          image: taksan/cimple-back:v2
          ports:
            - containerPort: 8000
              name: http
          env:
            - name: RUN_WITHOUT_DATABASE
              value: "false"
            - name: STORE_URL
              value: "http://store.dev.cimple.bootcamp"
            - name: STORE_USER
              value: storeuser
            - name: STORE_PASS
              value: storepass
            - name: TASK_EXECUTOR
              value: "/app/job-executor.sh"
          volumeMounts:
            - name: logs
              mountPath: /app/logs
          startupProbe:
            httpGet:
              path: /health
              port: http
            periodSeconds: 10
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /health
              port: http
            failureThreshold: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: http
            failureThreshold: 30
            periodSeconds: 10
        - name: cimple-eviewer-collector
          image: taksan/cimple-eviewer-collector:v1
          volumeMounts:
            - name: config-data
              mountPath: /opt/
            - name: logs
              mountPath: /app/logs
---
apiVersion: v1
kind: Service
metadata:
  name: cimple-back
  namespace: dev
spec:
  type: LoadBalancer
  selector:
    app: cimple-back
  ports:
    - protocol: TCP
      port: 80
      targetPort: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cimple-back
  namespace: dev
spec:
  ingressClassName: nginx
  rules:
    - host: back.dev.cimple.bootcamp
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cimple-back
                port:
                  number: 80
