apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob-trigger-test
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: task-trigger
            image: curlimages/curl:8.00.1
            command: ["/bin/sh", "-c"]
            args:
              - |
                curl -f -X POST -H 'X-CLIENT-ID: shell' 'http://cimple-back/tasks/8/trigger'
          restartPolicy: OnFailure
