apiVersion: apps/v1
kind: Deployment
metadata:
  name: cimple-back-deployment
  labels:
    app: cimple-back
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cimple-back
  template:
    metadata:
      name: cimple-back
      labels:
        app: cimple-back
    spec:
      serviceAccount: backend-sa
      volumes:
        - name: config-data
          emptyDir: {}
      initContainers:
        - name: init-config
          image: alpine
          command:
            - sh
            - -c
            - |
              cat <<EOF > /opt/config.json
              {
                "events_file": "/opt/audit_events.log",
                "peer_url" : "http://cimple-eviewer.audit.svc.cluster.local/api/events"
              }
              EOF
          volumeMounts:
            - name: config-data
              mountPath: /opt/
      containers:
        - name: cimple-back
          image: taksan/cimple-back:v2
          ports:
            - containerPort: 8000
              name: http
          env:
            - name: TASK_EXECUTOR
              value: /app/job-executor.sh
            - name: STORE_URL
              value: http://cimple-store
            - name: STORE_USER
              value: storeuser
            - name: STORE_PASS
              value: storepass
          volumeMounts:
            - name: config-data
              mountPath: /app/logs

          startupProbe:
            httpGet:
              path: /health
              port: http
            periodSeconds: 10
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /health
              port: http
            failureThreshold: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: http
            failureThreshold: 30
            periodSeconds: 10
        - name: cimple-eviewer-collector
          image: taksan/cimple-eviewer-collector:v1
          volumeMounts:
            - name: config-data
              mountPath: /opt/
