apiVersion: apps/v1
kind: Deployment
metadata:
  name: cimple-back-deployment
  labels:
    app: cimple-back
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cimple-back
  template:
    metadata:
      name: cimple-back
      labels:
        app: cimple-back
    spec:
      serviceAccount: backend-sa
      volumes:
        - name: config-data
          configMap:
            name: cimple-back-config
        - name: logs
          emptyDir: {}
      containers:
        - name: cimple-back
          image: taksan/cimple-back:v2
          ports:
            - containerPort: 8000
              name: http
          env:
            - name: TASK_EXECUTOR
              value: /app/job-executor.sh
            - name: STORE_URL
              value: http://cimple-store
            - name: STORE_USER
              valueFrom:
                secretKeyRef:
                  name: cimple-store-secret
                  key: db-user
            - name: STORE_PASS
              valueFrom:
                secretKeyRef:
                  name: cimple-store-secret
                  key: db-pass

          volumeMounts:
            - name: logs
              mountPath: /app/logs

          startupProbe:
            httpGet:
              path: /health
              port: http
            periodSeconds: 10
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /health
              port: http
            failureThreshold: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: http
            failureThreshold: 30
            periodSeconds: 10
        - name: cimple-eviewer-collector
          image: taksan/cimple-eviewer-collector:v1
          volumeMounts:
            - name: logs
              mountPath: /app/logs
            - name: config-data
              mountPath: /opt/
