apiVersion: apps/v1
kind: Deployment
metadata:
  name: cimple-store-deployment
  labels:
    app: cimple-store
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cimple-store
  template:
    metadata:
      name: cimple-store
      labels:
        app: cimple-store
    spec:
      volumes:
        - name: cimple-store-data
          persistentVolumeClaim:
            claimName: cimple-store-pvc
      securityContext:
        fsGroup: 1000
      containers:
        - name: cimple-store
          image: taksan/cimple-store:v1
          ports:
            - containerPort: 8001
              name: http
          volumeMounts:
            - name: cimple-store-data
              mountPath: /app/data
          env:
          - name: STORE_USER
            value: storeuser
          - name: STORE_PASS
            value: storepass

