apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: back-sa-role-bind
subjects:
 - kind: ServiceAccount
   name: backend-sa
roleRef:
  kind: Role
  name: job-executor
  apiGroup: rbac.authorization.k8s.io
