apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: job-executor
  namespace: dev-jobs
rules:
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: back-sa-role-bind
  namespace: dev-jobs
subjects:
 - kind: ServiceAccount
   name: backend-sa
   namespace: dev
roleRef:
  kind: Role
  name: job-executor
  apiGroup: rbac.authorization.k8s.io
