apiVersion: v1
kind: PersistentVolume
metadata:
  name: manual-store-pv
spec:
  storageClassName: manual
  capacity:
    storage: 50Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp"

