apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cimple-store-pvc
  annotations:
    volumeType: local
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
