apiVersion: v1
kind: PersistentVolume
metadata:
  name: cimple-store-pv
  annotations:
    volumeType: local
spec:
  storageClassName: manual
  capacity:
    storage: 50Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
