apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cronjob-executor-role-binding
subjects:
 - kind: ServiceAccount
   name: backend-sa
roleRef:
  kind: Role
  name: cron-job-executor
  apiGroup: rbac.authorization.k8s.io
