apiVersion: batch/v1
kind: CronJob
metadata:
  name: date-printer
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: print-date
            image: busybox
            command: ["/bin/sh", "-c", "date"]
          restartPolicy: OnFailure
