apiVersion: v1
kind: Pod
metadata:
 name: cimple-eviewer-collector
spec:
  volumes:
  - name: config-data
    emptyDir: {}
  initContainers:
  - name: init-config
    image: alpine
    command:
        - sh
        - -c
        - |
          cat <<EOF > /opt/config.json
          {
            "events_file": "/opt/config.json",
            "peer_url": "http://${POD_IP}:5000/api/events"
          }
          EOF
          cat /opt/config.json
    env:
    - name: POD_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
    volumeMounts:
    - name: config-data
      mountPath: /opt/
  containers:
  - name: cimple-eviewer-collector
    image: taksan/cimple-eviewer-collector:v1
    volumeMounts:
    - name: config-data
      mountPath: /opt/
