apiVersion: v1
kind: Pod
metadata:
  name: cimple-front
spec:
  containers:
  - name: cimple-front
    image: taksan/cimple-front:v1
    imagePullPolicy: Always
    ports:
    - containerPort: 80
      name: http
