apiVersion: v1
kind: Pod
metadata:
  name: cimple-back
spec:
  volumes:
   - name: config-data
     emptyDir: {}
  initContainers:
  - name: init-config
    image: alpine
    command:
    - sh
    - -c
    - |
      cat <<EOF > /opt/config.json
      {
        "events_file": "/opt/audit_events.log",
        "peer_url" : "http://192.168.162.131:5000/api/events"
      }
      EOF
    volumeMounts:
    - name: config-data
      mountPath: /opt/
  containers:
  - name: cimple-back
    image: taksan/cimple-back:v1
    ports:
    - containerPort: 8000
      name: http
    env:
    - name: RUN_WITHOUT_DATABASE
      value: "true"
    volumeMounts:
    - name: config-data
      mountPath: /app/logs
  - name: cimple-eviewer-collector
    image: taksan/cimple-eviewer-collector:v1
    volumeMounts:
    - name: config-data
      mountPath: /opt/

