apiVersion: apps/v1
kind: Deployment
metadata:
  name: cimple-back-deployment
  labels:
    app: cimple-back
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cimple-back
  template:
    metadata:
      name: cimple-back
      labels:
        app: cimple-back
    spec:
      volumes:
      - name: config-data
        emptyDir: {}
      - name: logs
        emptyDir: {}
      initContainers:
      - name: init-config
        image: alpine
        command:
        - sh
        - -c
        - |
          cat <<EOF > /opt/config.json
          {
            "events_file": "/app/logs/audit_events.log",
            "peer_url" : "http://192.168.162.131:5000/api/events"
          }
          EOF
        volumeMounts:
        - name: config-data
          mountPath: /opt/
      containers:
      - name: cimple-back
        image: taksan/cimple-back:v1
        ports:
        - containerPort: 8000
          name: http
        env:
        - name: RUN_WITHOUT_DATABASE
          value: "true"
        volumeMounts:
        - name: logs
          mountPath: /app/logs
      - name: cimple-eviewer-collector
        image: taksan/cimple-eviewer-collector:v1
        volumeMounts:
        - name: config-data
          mountPath: /opt/
        - name: logs
          mountPath: /app/logs